var password;

var pass1="201248220154382012482";

password=prompt('Please enter your password to view this page!',' ');

if (password==pass1)
{ 
    function m() {
    var r='',c='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    for ( var i = 0; i < 5; i++ ) {
      r += c.charAt(Math.floor(Math.random() * 36));
   }
   return r;
}

})
    alert("WELCOME DENNIS CRIPPS, ALPHA COMMANDING OFFICER")
}
    

else
   {
    alert("WRONG PASSWORD REFER TO ALPHA OFFICER HANDBOOK FOR AID")
    }
